#!/bin/bash
set -eu

MYPATH=$(realpath "$0")
MYPATH=$(dirname "${MYPATH}")

# shellcheck source=env
source "${MYPATH}/env"

OUT_NOISY_WARNINGS=noisy_warnings_route.log

# shellcheck source=vpr_common
source "${VPRPATH}/vpr_common"

parse_args "$@"

run_vpr --route

mv vpr_stdout.log route.log
