#!/bin/bash
set -eu

MYPATH=$(realpath "$0")
MYPATH=$(dirname "${MYPATH}")

# shellcheck source=env
source "${MYPATH}/env"

OUT_NOISY_WARNINGS=noisy_warnings_place.log

# shellcheck source=vpr_common
source "${VPRPATH}/vpr_common"

parse_args "$@"

if [[ -z $PCF ]]; then
    PCF=""
fi

if [[ -z $NET ]]; then
     echo "Please provide net file name"
     exit 1
fi

echo "Generating coinstrains ..."
symbiflow_generate_constraints "${EBLIF}" "${NET}" "${PART}" "${DEVICE}" "${ARCH_DEF}" "${PCF}"

run_vpr --fix_clusters constraints.place --place

mv vpr_stdout.log place.log
