#!/bin/bash
set -eu

MYPATH=$(realpath "$0")
MYPATH=$(dirname "${MYPATH}")

# shellcheck source=env
source "${MYPATH}/env"

OUT_NOISY_WARNINGS=noisy_warnings_rr_graph.log

# shellcheck source=vpr_common
source "${VPRPATH}/vpr_common"

parse_args "$@"

run_vpr_xml_rr_graph --pack
