#!/bin/bash
set -eu

MYPATH=$(realpath "$0")
MYPATH=$(dirname "${MYPATH}")

# shellcheck source=env
source "${MYPATH}/env"
echo "Writing bitstream ..."

FRM2BIT=()
if [[ -v FRAMES2BIT ]]; then
	FRM2BIT=(--frm2bit "${FRAMES2BIT}")
fi

OPTS=d:f:b:p:
LONGOPTS=device:,fasm:,bit:,part:

PARSED_OPTS=$(getopt --options="${OPTS}" --longoptions="${LONGOPTS}" --name "$0" -- "$@")
eval set -- "${PARSED_OPTS}"

DEVICE=""
FASM=""
BIT=""
PART=xc7a35tcpg236-1

while true; do
	case "$1" in
		-d|--device)
			DEVICE=$2
			shift 2
			;;
		-p|--part)
			PART=$2
			shift 2
			;;
		-f|--fasm)
			FASM=$2
			shift 2
			;;
		-b|--bit)
			BIT=$2
			shift 2
			;;
		--)
			break
			;;
		*)
			echo "Usage:"
			echo "symbiflow_write_bitstream (-f|--fasm) FASM_INPUT_FILE (-b|--bit) BIT_INPUT_FILE"
			echo "                          [(-d|--device) DEVICE_TYPE] [(-p|--part) PART_NAME]"
			exit 1
	esac
done

if [[ -z $DEVICE ]]; then
	DEVICE=$(find_device_from_part "${PART}")
fi

DBROOT=$(realpath "${DATABASE_DIR}/${DEVICE}")

if [[ -z $FASM ]]; then
	echo "Please provide fasm file name"
	exit 1
fi

if [[ -z $BIT ]]; then
	echo "Please provide bit file name"
	exit 1
fi

xcfasm \
	--db-root "${DBROOT}" \
	--part "${PART}" \
	--part_file "${DBROOT}/${PART}/part.yaml" \
	--sparse \
	--emit_pudc_b_pullup \
	--fn_in "${FASM}" \
	--bit_out "${BIT}" \
	"${FRM2BIT[@]}"

